-- CreateTable
CREATE TABLE "Member" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "uid" TEXT NOT NULL,
    "tid" INTEGER NOT NULL,
    "current" BOOLEAN NOT NULL DEFAULT true,
    "createtime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Member_uid_fkey" FOREIGN KEY ("uid") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Member_tid_fkey" FOREIGN KEY ("tid") REFERENCES "Team" ("team_id") ON DELETE RESTRICT ON UPDATE CASCADE
);
